package com.miaoShaProject.dao;

import com.miaoShaProject.dataObject.OrderInfoDO;
import com.miaoShaProject.dataObject.OrderInfoDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Sep 13 16:28:19 CST 2021
     */
    long countByExample(OrderInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Sep 13 16:28:19 CST 2021
     */
    int deleteByExample(OrderInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Sep 13 16:28:19 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Sep 13 16:28:19 CST 2021
     */
    int insert(OrderInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Sep 13 16:28:19 CST 2021
     */
    int insertSelective(OrderInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Sep 13 16:28:19 CST 2021
     */
    List<OrderInfoDO> selectByExample(OrderInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Sep 13 16:28:19 CST 2021
     */
    OrderInfoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Sep 13 16:28:19 CST 2021
     */
    int updateByExampleSelective(@Param("record") OrderInfoDO record, @Param("example") OrderInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Sep 13 16:28:19 CST 2021
     */
    int updateByExample(@Param("record") OrderInfoDO record, @Param("example") OrderInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Sep 13 16:28:19 CST 2021
     */
    int updateByPrimaryKeySelective(OrderInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Sep 13 16:28:19 CST 2021
     */
    int updateByPrimaryKey(OrderInfoDO record);
}