package com.miaoShaProject.dao;

import com.miaoShaProject.dataObject.PromoDO;
import com.miaoShaProject.dataObject.PromoDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Sep 14 11:24:42 CST 2021
     */
    long countByExample(PromoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Sep 14 11:24:42 CST 2021
     */
    int deleteByExample(PromoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Sep 14 11:24:42 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Sep 14 11:24:42 CST 2021
     */
    int insert(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Sep 14 11:24:42 CST 2021
     */
    int insertSelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Sep 14 11:24:42 CST 2021
     */
    List<PromoDO> selectByExample(PromoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Sep 14 11:24:42 CST 2021
     */
    PromoDO selectByPrimaryKey(Integer id);
    PromoDO selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Sep 14 11:24:42 CST 2021
     */
    int updateByExampleSelective(@Param("record") PromoDO record, @Param("example") PromoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Sep 14 11:24:42 CST 2021
     */
    int updateByExample(@Param("record") PromoDO record, @Param("example") PromoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Sep 14 11:24:42 CST 2021
     */
    int updateByPrimaryKeySelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Sep 14 11:24:42 CST 2021
     */
    int updateByPrimaryKey(PromoDO record);
}