package com.miaoShaProject.dao;

import com.miaoShaProject.dataObject.SequenceInfoDO;
import com.miaoShaProject.dataObject.SequenceInfoDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SequenceInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Sep 14 10:10:54 CST 2021
     */
    long countByExample(SequenceInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Sep 14 10:10:54 CST 2021
     */
    int deleteByExample(SequenceInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Sep 14 10:10:54 CST 2021
     */
    int insert(SequenceInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Sep 14 10:10:54 CST 2021
     */
    int insertSelective(SequenceInfoDO record);

    SequenceInfoDO getSequenceByName(String name);
    int updateByNameSelective(SequenceInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Sep 14 10:10:54 CST 2021
     */
    List<SequenceInfoDO> selectByExample(SequenceInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Sep 14 10:10:54 CST 2021
     */
    int updateByExampleSelective(@Param("record") SequenceInfoDO record, @Param("example") SequenceInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Sep 14 10:10:54 CST 2021
     */
    int updateByExample(@Param("record") SequenceInfoDO record, @Param("example") SequenceInfoDOExample example);
}